server:
  port: 9090

spring:
  application:
    name: nexus-platform

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexus_platform}
    username: ${DB_USERNAME:your-username}
    password: ${DB_PASSWORD:your-password}

jwt:
  secret: your-secret-key-here
  expiration: 86400000