apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: nexus-platform
type: Opaque
stringData:
  JWT_SECRET: nexus-platform-super-secret-key-2024-must-be-at-least-256-bits
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-platform
  namespace: nexus-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-platform
  template:
    metadata:
      labels:
        app: nexus-platform
    spec:
      containers:
        - name: nexus-platform
          image: ghcr.io/vikash1703/nexus-platform:latest
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/nexus_platform
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-platform
  namespace: nexus-platform
spec:
  selector:
    app: nexus-platform
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP
