apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-platform-ingress
  namespace: nexus-platform
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: nexus-platform.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus-platform
                port:
                  number: 9090
